Refactor frontend code, fix eslint warnings
antelovric1423/VehicleManagement pull request #1
Opened 2022-06-03 17:47 UTC by antelovric1423

2022-06-05 01:14 UTC, lukasaric requested changes
Nice job overall! Did the first pass. I'll take a look at the rest of the files I didn’t get to look at as soon as I catch some free time 😉

2022-06-05 01:14 UTC, lukasaric commented on backend/app.js
> -  origin: "http://localhost:8080"
This should be defined in `.env`as `APP_URL` since this URL represents the client-side of the app. Also, create a `.env.example` file with the empty values since env should be git ignored (update `.gitignore` file). And one more tiny detail, when you declare a variable in env you don’t need quotes when assigning the value 😉

2022-06-05 01:14 UTC, lukasaric commented on frontend/App.vue
> +      <Vehicles @createVehicle="createVehicle" @deleteVehicle="deleteVehicle" :vehicles="vehicles" />
```suggestion
      <vehicle-list @create="create" @delete="delete" :vehicles="vehicles" />
```
Go with the two word naming as it is written in the [style guide](https://v2.vuejs.org/v2/style-guide/?redirect=true). Also, use dash-case ☝️ 
As for the listeners and method naming, move this vehicle state management logic in the vehicles root index file and then you can simply use create, remove etc.

2022-06-05 01:14 UTC, lukasaric commented on frontend/App.vue
> +      fetch('http://localhost:3000/vehicles')
Use [axios](https://www.npmjs.com/package/axios) instead of the web API `fetch` method for creating HTTP requests to the server.
Also, you can create a file, e.g `frontend/api/vehicle.js`, and there expose all vehicle API endpoints using Axios. It should look something like this:
```js
import api from './api/vehicle';

return api.fetch()
  .then(...
```

p.s Ofc, this applies to the all methods bellow

2022-06-05 01:14 UTC, lukasaric commented on frontend/App.vue
> +import Vehicles from './components/Vehicles';
You can define basic alias in `vue.config` and use import like this:
```js
import Vehicles from '@/components/Vehicles';
```
`@` represents `frontend` folder

Here's the [example](https://github.com/vuejs/vue-cli/issues/2398#issuecomment-430355335) how to do it 😉

2022-06-05 01:14 UTC, lukasaric commented on frontend/App.vue
> +
Remove unnecessary empty lines between each prop/method.

2022-06-05 01:14 UTC, lukasaric commented on frontend/App.vue
> +        .catch(err => alert(err));
It would be good to create human-readable error/success message here too.
Since you're using vuetify it would be good to show these messages through the [snackbar](https://vuetifyjs.com/en/components/snackbars/).

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +              <v-text-field v-model="editedItem.make" label="Make" single-line required></v-text-field>
```suggestion
              <v-text-field
                 v-model="editedItem.make"
                 label="Make"
                 single-line required />
```

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +    <template v-slot:activator="{ on, attrs }">
Consider using shorthand for a v-slot
```suggestion
    <template #activator="{ on, attrs }">
```

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +  name: 'VehicleDialog',
```suggestion
  name: 'vehicle-dialog'
```

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +    editedItem: { make: "", model: "", year: null }
You can create `initItem` factory function above the export default:

```js
const initItem = () => ({ { make: '', model: '', year: null });
```

and use it here `editedItem: initItem()`

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +    defaultItem() {
You can remove this and use `initItem` below directly (add/close methods).

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +<style scoped>
omit unused styles

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +      const newItem = {
Do we need this? Why not just emit `this.editedItem` directly?

2022-06-05 01:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +      this.$emit("createVehicle", newItem);
```suggestion
      this.$emit('create', this.editedItem);
```
Use `dash-case` for the event name. Also, I noticed that you are using double quotes for strings, eslint does not warn you? Maybe you're missing one of the eslint packages such as `eslint-config-semistandard` or `eslint-config-standard`.

2022-06-06 08:57 UTC, lukasaric requested changes

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +<template>
Should we implement vehicle `edit` as well?

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +  name: 'ConfirmDialog',
`confirmation-dialog`

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +        <slot></slot>
Since the styles will be the same, does it make sense to pass `title` prop and just use it here like this:
```js
<v-card-title>{{ title }}</v-card-title>
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +  props: ["showDialog"],
You should write props like this:
```suggestion
  props: {
    show: { type: Boolean, required: true }
   },
```
Now you have an explicit type and it's required as well.

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +  props: ["vehicles"],
Since state-management will be handled here, this won't be needed

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +      <v-data-table dense :headers="headers" :items="this.vehicles" item-key="id" class="elevation-1"
```suggestion
   <v-data-table
      :headers="headers"
      :items="this.vehicles"
      :search="search"
      :loading="this.isLoading"
      loading-text="Loading... Please wait"
      item-key="id"
      dense
      class="elevation-1">
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +      return this.vehicles.length == 0;
What happens if we have 0 records in our DB?

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +      return this.vehicles.length == 0;
This should be handled by having the `isLoading` flag on `data`. You'll set it to `true` before hitting the fetch request, and after it's done you'll set it to `false`. Something like this:
```js
this.isLoading = true;
return this.fetch()
   ....
   .finally(() => { this.isLoading = false; });
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +<style scoped>
Remove this since it's unused

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +    headers: [{ text: 'Make', value: "make" },
This should belong to computed since this is something that is static and it should be immutable.
Also you can define it above the export like this:
```js
const headers = () => [
    { text: 'Make', value: "make" },
    { text: 'Model', value: "model" },
    { text: 'Year', value: "year" },
    { text: 'Actions', value: 'actions', sortable: false },
]

...

computed: {
   headers, // implicit assignment
   ...
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +  <v-dialog v-model="showDialog" max-width="500px">
`showDialog` is a prop it should not be v-model-ed since props should be immutable.
```suggestion
  <v-dialog :value="show" max-width="500px">
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +      this.$emit("dCancel");
```suggestion
      this.$emit("cancel");
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +      this.$emit("dConfirm");
```suggestion
      this.$emit("confirm");
```

2022-06-06 08:57 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +<style scoped>
Omit this

2022-06-07 16:58 UTC, antelovric1423 commented on frontend/App.vue
> +      <Vehicles @createVehicle="createVehicle" @deleteVehicle="deleteVehicle" :vehicles="vehicles" />
this throws errors as delete is javascript keyword

2022-06-07 17:06 UTC, lukasaric commented on frontend/App.vue
> +      <Vehicles @createVehicle="createVehicle" @deleteVehicle="deleteVehicle" :vehicles="vehicles" />
`@remove` shall do the trick then :)

2022-06-07 17:16 UTC, antelovric1423 commented on frontend/App.vue
> +
isnt it more readable like this?

2022-06-07 17:23 UTC, antelovric1423 commented on frontend/components/Vehicles/VehicleDialog.vue
> +      const newItem = {
i was not sure if objects are passed by reference so i created it, but i will remove.

2022-06-07 17:25 UTC, antelovric1423 commented on frontend/components/Vehicles/VehicleDialog.vue
> +      this.$emit("createVehicle", newItem);
done. it does warn but i used croatian keyboard so it is easier to use " " instead of ' '... i fixed those lints though through this commit.

2022-06-07 17:26 UTC, antelovric1423 commented on frontend/components/Vehicles/VehicleDialog.vue
> +<template>
in task specification they only requested create and delete, but whatever you want

2022-06-07 17:40 UTC, antelovric1423 commented on frontend/components/Vehicles/index.vue
> +  props: ["vehicles"],
you mean fetch and do updates from here insteaad of App.vue?

2022-06-07 17:47 UTC, antelovric1423 commented on frontend/components/Vehicles/index.vue
> +      <v-data-table dense :headers="headers" :items="this.vehicles" item-key="id" class="elevation-1"
editor doesnt let me save in so many lines, formats it to be compact, but i will reorder as you suggested

2022-06-07 18:05 UTC, antelovric1423 commented on frontend/components/Vehicles/ConfirmDialog.vue
> +  <v-dialog v-model="showDialog" max-width="500px">
why should props be immutable? how am i supposed to close this dialog then? what is the difference between value and vmodel in this case?

2022-06-08 06:50 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +<template>
We can do it after you address this comments ;)

2022-06-08 06:50 UTC, lukasaric commented on frontend/components/Vehicles/index.vue
> +  props: ["vehicles"],
Yeap

2022-06-08 07:14 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +      const newItem = {
@antelovric1423  Yeap, objects are passed by ref. On the other though, it's better to create a new object as you did. It will work as I suggested, but it's always better to emit newly cloned objects (sorry I was reviewing this in late hours 🙈 and nice catch! ).
There is very little chance that this will create any side effects due to the fact that we will use this object as a HTTP request payload and then we will continue to use its response. But you should still avoid broadcasting references because of the way javascript works. To summarize and simplify in the end, in Vue we will always send things from top to bottom and in the child components, we should NOT mutate them (so that there are no side effects in the root since it takes care of state management). When they reach the bottom, we broadcast the change all the way to the root component, which will eventually hydrate the new state.

2022-06-08 07:19 UTC, lukasaric commented on frontend/components/Vehicles/VehicleDialog.vue
> +      const newItem = {
@antelovric1423 Here's a link for [props](https://vuejs.org/guide/components/props.html#prop-passing-details) in Vue docs. Here everything is explained clearly. By the way, I advise you to search for all these things as much as possible from Vue docs because it is very good, and something that is JS specific, MDN is the right place to search for.

2022-06-08 07:29 UTC, lukasaric commented on frontend/components/Vehicles/ConfirmDialog.vue
> +  <v-dialog v-model="showDialog" max-width="500px">
As for the `props` question it's explained in `props` link that I posted in a previous comment 😉 
Difference between `v-model` and `value` is very simple, `v-model` equals to this:
```js
<v-dialog @input="showDialog = $event" :value="showDialog" /> // $event is shorthand, this can be written like this: @input="value => showDialog  = value"
...

data = () => ({ showDialog = false })

```

As for the closing dialog, you can achieve it in various ways. Since you have close/confirm button within the dialog, they will emit the event which in parent sets `showDialog` to false, which will be passed again here. Then `:value` on the dialog will be false and it should be closed. This should do the trick.

2022-06-17 13:57 UTC, merged